export const DataActionTypes = {
  SET_PIZZA: 'SET_PIZZAS',
  SET_LOADED_STATUS: 'SET_LOADED_STATUS',
};

export const FiltersActionTypes = {
  CHANGE_ACTIVE_FILTER: 'CHANGE_ACTIVE_FILTER',
  CHANGE_SORT_TYPE: 'CHANGE_SORT_TYPE',
};
