export const DataActionTypes = {
  SET_PIZZA: 'SET_PIZZAS',
  SET_LOADED_STATUS: 'SET_LOADED_STATUS',
};

export const FiltersActionTypes = {
  CHANGE_ACTIVE_FILTER: 'CHANGE_ACTIVE_FILTER',
  CHANGE_SORT_TYPE: 'CHANGE_SORT_TYPE',
};

export const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ALL_ITEMS: 'REMOVE_ALL_ITEMS',
  CALCULATE_COUNT_AND_PRICE: 'CALCULATE_COUNT_AND_PRICE',
  INCREMENT_CART_ITEM: 'INCREMENT_CART_ITEM',
  DECREMENT_CART_ITEM: 'DECREMENT_CART_ITEM',
};
